# Generated by Django 2.1.7 on 2019-02-26 19:47

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainCoreApp', '0004_remove_websubnavset_nav_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmake',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容'),
        ),
    ]
